on: push
name: Run tests
jobs:
  checks:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run tests
      uses: cedrickring/golang-action@1.6.0